### ISSUE TITLE
Multiple react error

### ISSUE THREAD

**Issue by ghost** [yarnball/SearchKitJWT#1]
Hey, I was looking for code like this!  Any chance of fixing the multiple react error?

**Comment by yarnball** [comment]
Hi, yep this was an easy fix. I just needed to install the latest version of SearchKit (betas).

Do this by running:

`npm install searchkit@1.0.0-7 --save`

**Comment by ghost** [comment]
Thanks!  Don't know why I overlooked trying this!

**Comment by yarnball** [comment]
No worries. I've been meaning to add Webpack, and enhance this a bit. Let me know if you do something with the project.
